---
- hosts: all
  become: true
  tasks:
  - name: update repository and install updates (Debian and Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian","Ubuntu"]
