---
- hosts: all
  become: true
  pre_tasks:
  - name: update repository and install updates (Debian and Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian","Ubuntu"]

- hosts: all
  become: true
  tasks:
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILZ38/L7rtQzrDktSp7C2cEM1CjYEpSzebM6pc6ZNtuD ansible"